fix: Change useIssues from useSWRInfinite to useSWR.
Due to typescript error

> error TS4023: Exported variable 'useIssues' has or is using name 'SWRInfiniteMutatorOptions' from external module "/Users/ryohidaka/Workspace/npm/use-backlog/node_modules/swr/dist/infinite/index" but cannot be named.